package br.com.pokedex.model.Pokemon

enum class TipoPokemon {
    NORMAL, PLANTA, FOGO, AGUA, VOADOR, GELO, PEDRA, TERRESTRE, ACO, LUTADOR, SOMBRIO, PSIQUICO, VENENOSO, INSETO, FADA, FANTASMA, DRAGAO
}